from fuzzywuzzy import fuzz

class CountryFinder:
    def __init__(self):

        self.countries = {
            "afghanistan": "Afghanistan",
            "albania": "Albania",
            "algeria": "Algeria",
            "andorra": "Andorra",
            "angola": "Angola",
            "anguilla": "Anguilla",
            "antigua": "Antigua & Barbuda",
            "antigua & deps": "Antigua & Barbuda",
            "antigua & barbuda": "Antigua & Barbuda",
            "antigua and barbuda": "Antigua & Barbuda",
            "antigua and deps": "Antigua & Barbuda",
            "argentina": "Argentina",
            "armenia": "Armenia",
            "aruba": "Aruba",
            "australia": "Australia",
            "austria": "Austria",
            "azerbaijan": "Azerbaijan",
            "bahamas": "Bahamas",
            "bahrain": "Bahrain",
            "bangladesh": "Bangladesh",
            "barbados": "Barbados",
            "belarus": "Belarus",
            "belgium": "Belgium",
            "belize": "Belize",
            "benin": "Benin",
            "bermuda": "Bermuda",
            "bhutan": "Bhutan",
            "bolivia": "Bolivia",
            "bosnia": "Bosnia & Herzegovina",
            "bosnia herzegovina": "Bosnia & Herzegovina",
            "bosnia & herzegovina": "Bosnia & Herzegovina",
            "bosnia and herzegovina": "Bosnia & Herzegovina",
            "botswana": "Botswana",
            "brazil": "Brazil",
            "british indian ocean territory":  "British Indian Ocean Territory",
            "british virgin islands": "British Virgin Islands",
            "uk islands": "British Virgin Islands",
            "us virgin islands": "US Virgin Islands",
            "brunei": "Brunei",
            "bulgaria": "Bulgaria",
            "burkina": "Burkina Faso",
            "burkina Faso": "Burkina Faso",
            "burundi": "Burundi",
            "cambodia": "Cambodia",
            "cameroon": "Cameroon",
            "canada": "Canada",
            "cape verde": "Cape Verde",
            "capo verde": "Cape Verde",
            "caymans": "Cayman Islands",
            "cayman islands": "Cayman Islands",
            "central african republic": "Central African Republic",
            "chad": "Chad",
            "chile": "Chile",
            "china": "China",
            "hong kong china": "China (Hong Kong)",
            "hong kong": "China (Hong Kong)",
            "christmas island": "Christmas Island",
            "colombia": "Colombia",
            "comoros": "Comoros",
            "congo": "Congo",
            "cook islands": "Cook Islands",
            "democratic republic of the congo": "Democratic Republic of the Congo",
            "costa rica": "Costa Rica",
            "croatia": "Croatia",
            "cuba": "Cuba",
            "cyprus": "Cyprus",
            "czech republic": "Czech Republic",
            "czechia": "Czech Republic",
            "denmark": "Denmark",
            "djibouti": "Djibouti",
            "dominica": "Dominica",
            "dominican republic": "Dominican Republic",
            "east timor": "East Timor",
            "timor leste": "East Timor",
            "timor east": "East Timor",
            "ecuador": "Ecuador",
            "egypt": "Egypt",
            "el salvador": "El Salvador",
            "equatorial Guinea": "Equatorial Guinea",
            "eritrea": "Eritrea",
            "estonia": "Estonia",
            "ethiopia": "Ethiopia",
            "falklands": "Falkland Islands",
            "falkland islands": "Falkland Islands",
            "faroe islands": "Faroe Islands",
            "faeroe": "Faroe Islands",
            "islas malvinas": "Falkland Islands",
            "fiji": "Fiji",
            "finland": "Finland",
            "france": "France",
            "french polynesia": "French Polynesia",
            "polynesia": "French Polynesia",
            "gabon": "Gabon",
            "gambia": "Gambia",
            "georgia": "Georgia",
            "germany": "Germany",
            "ghana": "Ghana",
            "gibraltar": "Gibraltar",
            "greece": "Greece",
            "greenland": "Greenland",
            "grenada": "Grenada",
            "guam": "Guam",
            "guatemala": "Guatemala",
            "guernsey": "Guernsey",
            "guinea": "Guinea",
            "guinea-Bissau": "Guinea-Bissau",
            "guyana": "Guyana",
            "haiti": "Haiti",
            "honduras": "Honduras",
            "hungary": "Hungary",
            "iceland": "Iceland",
            "india": "India",
            "indonesia": "Indonesia",
            "iran": "Iran",
            "iraq": "Iraq",
            "ireland": "Ireland",
            "isle of man": "Isle of Man",
            "israel": "Israel",
            "italy": "Italy",
            "ivory Coast": "Ivory Coast",
            "côte d'ivoire": "Ivory Coast",
            "cote d'ivoire": "Ivory Coast",
            "jamaica": "Jamaica",
            "japan": "Japan",
            "jersey": "Jersey",
            "jordan": "Jordan",
            "kazakhstan": "Kazakhstan",
            "kenya": "Kenya",
            "kiribati": "Kiribati",
            "south korea": "South Korea",
            "korea south": "South Korea",
            "korea": "South Korea",
            "kosovo": "Kosovo",
            "kuwait": "Kuwait",
            "kyrgyzstan": "Kyrgyzstan",
            "laos": "Laos",
            "latvia": "Latvia",
            "lebanon": "Lebanon",
            "lesotho": "Lesotho",
            "liberia": "Liberia",
            "libya": "Libya",
            "liechtenstein": "Liechtenstein",
            "lithuania": "Lithuania",
            "luxembourg": "Luxembourg",
            "macao": "Macau",
            "macau": "Macau",
            "macedonia": "North Macedonia",
            "macedonia republic": "North Macedonia",
            "republic of macedonia": "North Macedonia",
            "north macedonia": "North Macedonia",
            "fyrom": "North Macedonia",
            "madagascar": "Madagascar",
            "malawi": "Malawi",
            "malaysia": "Malaysia",
            "maldives": "Maldives",
            "mali": "Mali",
            "malta": "Malta",
            "marshall islands": "Marshall Islands",
            "marshalls": "Marshall Islands",
            "martinique": "Martinique",
            "mauritania": "Mauritania",
            "mauritius": "Mauritius",
            "mexico": "Mexico",
            "micronesia": "Micronesia",
            "moldova": "Moldova",
            "monaco": "Monaco",
            "mongolia": "Mongolia",
            "montenegro": "Montenegro",
            "montserrat": "Montserrat",
            "morocco": "Morocco",
            "mozambique": "Mozambique",
            "myanmar": "Myanmar",
            "burma": "Myanmar",
            "namibia": "Namibia",
            "nauru": "Nauru",
            "nepal": "Nepal",
            "netherlands": "Netherlands",
            "holland": "Netherlands",
            "new caledonia": "New Caledonia",
            "new zealand": "New Zealand",
            "nicaragua": "Nicaragua",
            "niger": "Niger",
            "nigeria": "Nigeria",
            "niue": "Niue",
            "norway": "Norway",
            "oman": "Oman",
            "pakistan": "Pakistan",
            "palau": "Palau",
            "palestine": "Palestinian Territories",
            "palestinian state": "Palestinian Territories",
            "palestinian territory": "Palestinian Territories",
            "palestinian territories": "Palestinian Territories",
            "gaza": "Palestinian Territories",
            "gaza strip": "Palestinian Territories",
            "west bank": "Palestinian Territories",
            "panama": "Panama",
            "papua new guinea": "Papua New Guinea",
            "paraguay": "Paraguay",
            "peru": "Peru",
            "philippines": "Philippines",
            "poland": "Poland",
            "portugal": "Portugal",
            "puerto rico": "Puerto Rico",
            "porto rico": "Puerto Rico",
            "qatar": "Qatar",
            "romania": "Romania",
            "russian federation": "Russia",
            "russia": "Russia",
            "rwanda": "Rwanda",
            "saint helena, ascension and tristan da cunha": "Saint Helena, Ascension and Tristan da Cunha",
            "st helena": "Saint Helena, Ascension and Tristan da Cunha",
            "ascension": "Saint Helena, Ascension and Tristan da Cunha",
            "tristan da cunha": "Saint Helena, Ascension and Tristan da Cunha",
            "st kitts & nevis": "St Kitts & Nevis",
            "st kitts and nevis": "St Kitts & Nevis",
            "st lucia": "Saint Lucia",
            "saint lucia": "Saint Lucia",
            "saint vincent & the grenadines": "Saint Vincent & the Grenadines",
            "saint vincent and the grenadines": "Saint Vincent & the Grenadines",
            "saint vincent": "Saint Vincent & the Grenadines",
            "samoa": "Samoa",
            "san marino": "San Marino",
            "sao tome & principe": "Sao Tome & Principe",
            "sao tome and principe": "Sao Tome & Principe",
            "saudi": "Saudi Arabia",
            "saudi arabia": "Saudi Arabia",
            "senegal": "Senegal",
            "serbia": "Serbia",
            "seychelles": "Seychelles",
            "sierra leone": "Sierra Leone",
            "singapore": "Singapore",
            "slovakia": "Slovakia",
            "slovenia": "Slovenia",
            "solomon islands": "Solomon Islands",
            "solomons": "Solomon Islands",
            "somalia": "Somalia",
            "south africa": "South Africa",
            "south sudan": "South Sudan",
            "spain": "Spain",
            "saint vincent and the grenadines": "Saint Vincent and the Grenadines",
            "saint vincent": "Saint Vincent and the Grenadines",
            "st. vincent and the grenadines": "Saint Vincent and the Grenadines",
            "st. vincent": "Saint Vincent and the Grenadines",
            "sri lanka": "Sri Lanka",
            "sudan": "Sudan",
            "suriname": "Suriname",
            "swaziland": "Swaziland",
            "sweden": "Sweden",
            "switzerland": "Switzerland",
            "syria": "Syria",
            "taiwan": "Taiwan",
            "tajikistan": "Tajikistan",
            "tanzania": "Tanzania",
            "thailand": "Thailand",
            "togo": "Togo",
            "tonga": "Tonga",
            "trinidad & tobago": "Trinidad & Tobago",
            "trinidad": "Trinidad & Tobago",
            "tobago": "Trinidad & Tobago",
            "tunisia": "Tunisia",
            "turkey": "Turkey",
            "turkmenistan": "Turkmenistan",
            "turks": "Turks & Caicos",
            "caicos": "Turks & Caicos",
            "turks and caicos": "Turks & Caicos",
            "tuvalu": "Tuvalu",
            "uganda": "Uganda",
            "ukraine": "Ukraine",
            "united arab emirates": "United Arab Emirates",
            "emirates": "United Arab Emirates",
            "uae": "United Arab Emirates",
            "united kingdom": "United Kingdom",
            "great britain": "United Kingdom",
            "britain": "United Kingdom",
            "uk": "United Kingdom",
            "wales": "United Kingdom",
            "scotland": "United Kingdom",
            "northern ireland": "United Kingdom",
            "england": "United Kingdom",
            "united states": "United States",
            "usa": "United States",
            "usa": "United States",
            "america": "United States",
            "united states of america": "United States",
            "uruguay": "Uruguay",
            "uzbekistan": "Uzbekistan",
            "vanuatu": "Vanuatu",
            "vatican city": "Vatican City",
            "vatican": "Vatican City",
            "venezuela": "Venezuela",
            "vietnam": "Vietnam",
            "virgin islands": "Virgin Islands",
            "yemen": "Yemen",
            "zambia": "Zambia",
            "zimbabwe": "Zimbabwe",
        }

        self.phoneline_from_country = {
            "Afghanistan": ["Afghanistan Emergency Hotline (open 24 hours): 119"],
            "Albania": ["Linja e Jetës / Life Line (10am-2pm): 0800 12345"],
            "Algeria": ["Algeria Suicide Helpline: 0021 3983 2000 58"],
            "Andorra": ["Andorra Emergency Hotline (open 24 hours): 112"],
            "Angola": ["Angola Emergency Hotline (open 24 hours): 113"],
            "Anguilla": ["Angola Emergency Hotline (open 24 hours): 911"],
            "Antigua & Barbuda": ["Antigua & Barbuda Emergency Hotline (open 24 hours): 911"],
            "Argentina": ["Centro de Valorizacion de la Vida Samaritanos: 054 022 3493 0430", 
                          "S.O.S. Un Amigo Anonimo: (054 011) 4783 8888",
                          "Teléfono de la Esperanza: 902 500 002",
                          "Programa de Prevención, Atención y Posvención del Suicidio: (054 011) 4664 1936"],
            "Armenia": ["Trust Social Work and Sociological Research Centre: (2) 538194 / (2) 538197"],
            "Aruba": ["Aruba Emergency Hotline (open 24 hours): 911"],
            "Australia": ["Lifeline Australia: 13 11 14",
                          "Lifelink Samaritans: 03 63 31 3355",
                          "Suicide Call Back Service: 1300 659 467",
                          "MensLine Australia: 1300 78 99 78",
                          "SANE Helpline: 1800 187 263"],
            "Austria": ["Telefonseelsorge: 142",
                        "Emotional support helpline: 116123"],
            "Azerbaijan": ["Crisis Helpline for Young People: 510-66-36",
                           "Azerbaijan Emergency Hotline (open 24 hours): 112"],
            "Bahamas": ["Bahamas Crisis Centre: 328-0922 / 322-4999",
                        "National Suicide Hotline: 322-2763"],
            "Bahrain": ["Helpline: 0097 161 199 168 / 188 / 191 / 334"],
            "Bangladesh": ["Moner Bondhu Helpline (open 24 hours): 8801776632344"
                           "Kaan Pete Roi (GP): 01779554391, 01779554392",
                           "Kaan Pete Roi (Airtel): 01688709965, 01688709966",
                           "Kaan Pete Roi (Banglalink): 01985275286",
                           "Kaan Pete Roi (Robi): 01852035634"],
            "Barbados": ["Samaritans of Barbados: (246) 4299999"],
            "Belarus": ["Minsk Regional Clinical Centre 'Psychiatry-Addiction' (open 24 hours): 375 (17) 311-00-99 (landline phone) / 375 (29) 899 04 01 (Telegram, Whatsapp, Viber) / 375 (29) 101-73-73 (A1)"],
            "Belgium": ["Tele-Onthaal: 106",
                        "Le Centre de Prévention du Suicide: 0800 32 123",
                        "Vlaams Expertisecentrum Suïcidepreventie: 1813"],
            "Belize": ["Belize Emergency Hotline (open 24 hours): 911"],
            "Benin": ["Benin Emergency Hotline (open 24 hours): 117"],
            "Bermuda": ["Acute Community Mental Health Service (Mon-Fri 8am-5pm): 239 2261",
                        "Helpline (after hours and weekends): 236 3770"],
            "Bhutan": ["Health Help Center (open 24 hours): 112"],
            "Bolivia": ["Bolivia Suicide Hotline: 3911270"
                        "Telefono de la Esperanza (Cochabamba): (00 591 4) 4 25 42 42",
                        "Telefono de la Esperanza (La Paz): 2248486 / 75288084"],
            "Bosnia & Herzegovina": ["Plavi Telefon (9am-5pm): 080 05 03 05"],
            "Botswana": ["National Counselling Line (open 24 hours): 0861 322 322"
                         "Botswana Suicide Hotline: 3911270/290",
                         "Lifeline/FTMTB: 267 7552 7590"],
            "Brazil": ["Centro de Valorização da Vida: 188"],
            "British Indian Ocean Territory": ["Emergency Hotline (open 24 hours): 999"],
            "British Virgin Islands": ["Emergency Hotline (open 24 hours): 911 / 999"],
            "US Virgin Islands": ["Emergency Hotline (open 24 hours): 911"],
            "Brunei": ["Hope Line 145 (8am-11pm): 145",
                       "Helpline 141 Mental Health Support: 141"],
            "Bulgaria": ["Sofia Hotline: 0035 9249 17 223"],
            "Burkina Faso": ["Burkina Faso Emergency Hotline (open 24 hours): 17"],
            "Burundi": ["Human Health Aid Burundi: 00257 22 23 53 78"],
            "Cambodia": ["TPO Cambodia: 855 17 222 372 / 010 222 478 / 097 9111 918 / 089 666 325"],
            "Cameroon": ["Cameroon Emergency Hotline (open 24 hours): 17117"],
            "Canada": ["Crisis Services Canada: 1.833.456.4566",
                       "Crisis Services Canada (Text messages number): 45645",
                       "1-800-SUICIDE: 1-800-784-2433",
                       "TTY: 1-866-872-0113",
                       "The Seniors' Distress Line: 604-872-1234",
                       "Mental Health Support: 310-6789",
                       "KUU-US Crisis Line Society: 250-723-4050"],
            "Cape Verde": ["Cape Verde Emergency Hotline (open 24 hours): 132"],
            "Cayman Islands": ["Crisis Hotline (open 24 hours): 943-2422",
                               "HSA Mental Health Team: 949-8600",
                               "The Counselling Centre: 949-8789"],
            "Central African Republic": ["Central African Republic Emergency Hotline (open 24 hours): 611253"],
            "Chad": ["Chad Emergency Hotline (open 24 hours): 17"],
            "Chile": ["Teléfono de la Esperanza: (00 56 42) 22 12 00"],
            "China": ["Lifeline: 400 821 1215",
                      "Lifeline Yanji: (0433) 273 9595",
                      "Beijing Suicide Research and Prevention Center Hotline (Free): 0800-810-1117",
                      "Beijing Suicide Research and Prevention Center Hotline (Mobile/IP/extension users): 010-8295-1332"],
            "Christmas Island": ["Emergency Hotline (open 24 hours): 000"],
            "Colombia": ["Telefono de la Esperanza (Barranquilla): (00 57 5) 372 27 27",
                         "Telefono de la Esperanza (Bogota): (57-1) 323 24 25",
                         "Telefono de la Esperanza (Medellin): (00 57 4) 284 66 00",
                         "Telefono de la Esperanza (San Juan de Pasto): 3016326701"],
            "Comoros": ["Comoros Emergency Hotline (open 24 hours): 269 772 03 73"],
            "Congo": ["Congo Emergency Hotline (open 24 hours): 117"],
            "Cook Islands": ["Te Kainga O Pa Taunga (open 24 hours): 20162",
                             "Youthline (open 24 hours): 0800 4357 / SMS: 4357"],
            "Democratic Republic of the Congo": ["Emergency Hotline (open 24 hours): 112"],
            "Costa Rica": ["Costa Rica Suicide Hotline: 506-253-5439",
                           "Aqui Estoy/Here I Am line (Mon-Fri 2pm-10pm): 506-2272-3774)"],
            "Croatia": ["Plavi Telefon: (01) 4833-888"],
            "Cuba": ["Cuba Suicide Hotline: 532 348 14 49"],
            "Cyprus": ["Cyprus Samaritans: 8000 7773",
                       "Emotional support helpline: 116123"],
            "Czech Republic": ["Modrá Linka (Line 1): +420 549241010",
                               "Modrá Linka (Line 2/WhatsApp): +420 608902401",
                               "Pražská linka důvěry: 222 580 697",
                               "Linka důvěry Ostrava: 596 618 908 / 737 267 939"],
            "Denmark": ["Livslinien: +45 70 201 201",
                        "Psykiatrifonden, Mental Health Helpline (also in English): 39 25 25 25",
                        "Startlinjen - Start Line (4pm-11pm): 3536 2600"],
            "Djibouti": ["Djibouti Emergency Hotline (open 24 hours): 17"],
            "Dominica": ["Dominica Emergency Hotline (open 24 hours): 333 / 999"],
            "Dominican Republic": ["Línea Familiar Contigo (open 24 hours): 809-636-3507"],
            "East Timor": ["East Timor Emergency Hotline (open 24 hours): 112"],
            "Ecuador": ["Telefono De La Esperanza: 593 2 6000477 / 593 2 2923327"],
            "Egypt": ["Befrienders Cairo: 762 1602 / 762 1603 / 762 2381"],
            "El Salvador": ["El Salvador Emergency Hotline (open 24 hours): 911"],
            "Equatorial Guinea": ["Equatorial Guinea Emergency Hotline (open 24 hours): 114"],
            "Eritrea": ["Eritrea Emergency Hotline (open 24 hours): 12-77-99"],
            "Estonia": ["Eluliin (Estonian Lifeline): +372 6558088",
                        "USALDUS: 126 / 127"],
            "Ethiopia": ["Ethiopia Emergency Hotline (open 24 hours): 991 / 997"],
            "Falkland Islands": ["Emergency Hotline (open 24 hours): 28100 / 999"],
            "Faroe Islands": ["Red Cross Faroe Islands (Psychological counseling helpline): 788870"],
            "Fiji": ["Lifeline Fiji: 132454",
                     "Ba Methodist Lifeline Counselling Service: (0679) 670565",
                     "Wesley Church Counselling Services (Lifeline): (0679) 302998"],
            "Finland": ["Itsemurhien ehkäisykeskus, SOS - palvelu: 09-731391 / 040-5032199",
                        "Suomen Mielenterveysseura: 01019 5202"],
            "France": ["SOS Help: 01 46 21 46 46",
                       "S.O.S Amitié: 09 72 39 40 50",
                       "Suicide Ecoute: 01 45 39 40 00",
                       "E.P.E. idF. Fil Sante Jeunes: 0800 235 236",
                       "Fédération S.O.S Amitié France: 01 40 09 15 22"],
            "French Polynesia": ["Emergency Medical Assistance Hotline (ope 24 hours): 15"],
            "Gabon": ["Gabon Emergency Hotline (open 24 hours): 1730"],
            "Gambia": ["Gambia Emergency Hotline (open 24 hours): 17",
                       "National Helpline (for women): 1313"],
            "Georgia": ["Georgia Emergency Hotline (open 24 hours): 113"],
            "Germany": ["Die TelefonSeelsorge Emotional Support Helpline: 116 123",
                       "Telefonseelsorge (open 24 hours): 0800 1110 111 / 0800 1110 222",
                        "International Helpline Berlin: 030-44 01 06 07"],
            "Ghana": ["National Lifeline: 2332 444 71279",
                      "Lifeline Ghana (open 24 hours): 233 244 846 701"],
            "Gibraltar": ["GibSams (Mon-Fri 3pm-11pm, Sat-Sun 6pm-11pm): 116123"],
            "Greece": ["24 Hour Suicide Prevention Line: 1018",
                       "Life Line Hellas Emotional support helpline: 116123"],
            "Greenland": ["Tusaannga: 80 11 80 / SMS: 1899"],
            "Grenada": ["Grenada Emergency Hotline (open 24 hours): 911 / 439-1231"],
            "Guam": ["Emergency Hotline: 911"],
            "Guatemala": ["Guatemala Emergency Hotline (open 24 hours): 110"],
            "Guernsey": ["Guernsey Samaritans LBG (open 24 hours): 116 123"],
            "Guinea": ["Guinea Emergency Hotline (open 24 hours): 18"],
            "Guinea-Bissau": ["Guinea-Bissau Emergency Hotline (open 24 hours): 119"],
            "Guyana": ["Guyana Inter-agency Suicide Prevention Hotline: (+592) 223-0001 / 223-0009 / 600-7896 / 623-4444"],
            "Haiti": ["Asistans Sikolojik an IJANS: 2919 9000"],
            "Honduras": ["Telefono de la Esperanza: (00 504) 2558 08 08",
                         "Crisis Line San Pedro Sula (open 24 hours): (00 504) 2558 08 08",
                         "Crisis Line Tegucigalpa (open 24 hours): (00 504) 2232 13 14 / 2232 27 07"],
            "China (Hong Kong)": ["The Samaritans Hong Kong: 2896 0000",
                                  "The Samaritan Befrienders Hong Kong: 2389 2222"],
            "Hungary": ["Emotional support helpline (open 24 hours): 116 123"],
            "Iceland": ["Hjálparsíma (open 24 hours): 1717"],
            "India": ["1 Life, Crisis Support, Suicide Prevention (open 24 hours): 78930 78930",
                      "Lifeline Foundation (10am-6pm): 0332 4637437",
                      "Jeevan Aastha Helpline: 0091 6576453841",
                      "SAATH (1pm-7pm): 0091 79 26305544",
                      "SNEHA (open 24 hours): 4424640050",
                      "SAHAI Helpline: +91 80 2549 7777"],
            "Indonesia": ["Kementerian Kesehatan: 500-454",
                          "Saveyourselves.id Jakarta: (+62) 813 14988214 / 812 87877479 / 812 90704035 / 822 46514726 / 812 85651224"],
            "Iran": ["Iran Organization of Well Being (6am-9pm): 1480"],
            "Iraq": ["Emergency Hotline: 112 / 911"],
            "Ireland": ["Samaritans Ireland: 116 123 / 1850 60 90 90 (local rate) / 1850 60 90 91 (minicom)"],
            "Isle of Man": ["Isle of Man Samaritans: 116 123"],
            "Israel": ["ERAN: 1201 / 972 9 8891333 / 972 76 8844400"],
            "Italy": ["Samaritans - ONLUS: 800 86 00 22",
                      "Telefono Amico Italia: 199 284 284"],
            "Ivory Coast": ["Emergency Hotline (open 24 hours): 185"],
            "Jamaica": ["Hotline: 1-888-429-KARE (5273)"],
            "Japan": ["Befrienders International, Tokyo: +81 (0) 3 5286 9090",
                      "BI Suicide Prevention Centre, Osaka: Hotline: +81 (0) 6 4395 4343",
                      "Tell Lifeline (Counselling): 03 5774 0992",
                      "Tell Lifeline (Face to face): 03 3498 0231"],
            "Jersey": ["Samaritans of Jersey: 116 123"],
            "Jordan": ["Amman: 0096 262 508 900 / 902 / 903 / 904 / 939 / 941"],
            "Kazakhstan": ["Teens and Youth Crisis Helpline: 111",
                           "Телефон Доверия 150 (children and adolescents): 150",
                           "Emergency Hotline Kazakhstan (open 24 hours): 112"],
            "Kenya": ["Befrienders Kenya: 020 2051323",
                      "Befrienders Kenya (SMS line): 00254 707 633 692 / 00254 733 656 262 / 00254 775 388 222"],
            "Kiribati": ["Kiribati Women and Children Support Centre: 191",
                         "Kiribati Emergency Hotline (open 24 hours): 999 / 994"],
            "South Korea": ["Love-Line (Sarang - Jonwha) Counselling Centre: (2) 715 8600 / 716 8600 / 717 8600 / 718 8600",
                            "Counsel24: 1566-2525",
                            "LifeLine Korea: 1588-9191",
                            "Lifeline National Office: (82) 51 804 0896"],
            "Kosovo": ["Linja e Jetës (2pm-2am): 0800 12345"],
            "Kuwait": ["Kuwait Suicide Hotline Number: 22440904 / 22440905",
                       "KCMH Suicide Hotline (8am-5pm): 24621770"],
            "Kyrgyzstan": ["Kyrgyzstan Medical Service: 151"],
            "Laos": ["Laos Emergency Hotline (open 24 hours): 21-2706"],
            "Latvia": ["Skalbes: 371 67222922 / 371 27722292"],
            "Lebanon": ["Hotline (12 pm - 2 am): 1564"],
            "Lesotho": ["Lesotho Emergency Hotline (open 24 hours): 123"],
            "Liberia": ["Lifeline Liberia: 6534308"],
            "Libya": ["Libyan Psychosocial Support Team (9am-9pm every day except Friday): 1417"],
            "Liechtenstein": ["Liechtenstein Emergency Hotline (open 24 hours): 112"],
            "Lithuania": ["Vilties linija (Hope line): 116 123"],
            "Luxembourg": ["SOS Détresse - Hëllef iwwer Telefon: 454545"],
            "Macau": ["The Life Hope Hotline (Chinese): 2852 5222", 
                      "Expat Life Hope Hotline (English): 2852 5777"],
            "North Macedonia": ["Crisis Center 'Hope': (389) 2 3173 424 / (389) 2 3175 516"],
            "Madagascar": ["Madagascar Emergency Hotline (open 24 hours): 117"],
            "Malawi": ["Suicide Prevention Group: +265 888 11 46 26"],
            "Malaysia": ["Lifeline Association of Malaysia: (063) 92850039 / (063) 92850279 / (063) 92850049",
                         "Befrienders Malacca: (06) 284 2500",
                         "Befrienders Penang: (04) 281 5161 / (04) 281 1108",
                         "Befrienders Kuala Lumpur: (03) 7956 8144 / (03) 7956 8145",
                         "Befrienders Ipoh: (05) 547 7933 / (05) 547 7599",
                         "Befrienders Seremban: (06) 7653588 / 06 7653589"],
            "Maldives": ["Maldivian Red Crescent Mental Helpline (12pm-12am): 1425"],
            "Mali": ["Mali Emergency Hotline (open 24 hours): 17"],
            "Malta": ["Appogg Supportline: 179"],
            "Marshall Islands": ["Republic of the Marshall Islands Emergency Hotline (open 24 hours): 007"],
            "Martinique": ["Martinique Emergency Hotline (open 24 hours): 112"],
            "Mauritania": ["Mauritania Emergency Hotline (open 24 hours): 117"],
            "Mauritius": ["Befrienders Mauritius: 800 93 93 / 46 48 889"],
            "Mexico": ["Hotline: 525-510-2550",
                       "Programa Salvemos Una Vida: 9453777",
                       "SAPTEL: 018004727835"],
            "Micronesia": ["Chuuk State Hospital: (+691) 330 2216 / (691) 330 2444",
                           "Arthur Sigrah Memorial Hospital, Kosrae: (+691) 370 3199 / (+691) 370 3012",
                           "Yap State Hospital: (+691) 350 2115 / (+691) 350 3446",
                           "Pohnpei State Hospital: (+691) 320 2214 / (+691) 320 2215 / (+691) 320 2216"],
            "Moldova": ["Altruism Association Moldova (12pm-5pm): 37360806623"],
            "Monaco": ["Monaco Emergency Hotline (open 24 hours): 112"],
            "Mongolia": ["Mongolia Mental Health Hotline (open 24 hours): (+976) 1800-2000"],
            "Montenegro": ["Montenegro Emergency Hotline (open 24 hours): 112"],
            "Montserrat": ["Montserrat Emergency Hotline (open 24 hours): 1 (664) 491-2527"],
            "Morocco": ["Centre d'Etude et de Prévention du Suicide: 022 382 42 42",
                        "Sourire de Reda (Befrienders Casablanca): 212 (5) 22 87 47 40 / 212 (6) 62 58 95 70"],
            "Mozambique": ["Mozambique Emergency Hotline (open 24 hours): 119"],
            "Myanmar": ["Myanmar Emergency Hotline (open 24 hours): 999 / 119"],
            "Namibia": ["LifeLine Namibia: (09264) 61-232-221"],
            "Nauru": ["Nauru Emergency Hotline (open 24 hours): 911"],
            "Nepal": ["TUTH Suicide Hotline (open 24 hours): 16600121600",
                      "National Suicide Prevention helpline (8am-8pm): 1166",
                      "Mental Health Helpline Nepal (8am-8pm): 1660-0133666",
                      "Patan Hospital Suicide Hotline: 9813476123"],
            "Netherlands": ["113 Suicide Prevention (113 Zelfmoordpreventie): 0900-0113"],
            "New Caledonia": ["SOS écoute: 05 30 30"],
            "New Zealand": ["New Zealand Samaritans: 0800 726 666"
                            "1737.org: 1737",
                            "National Depression Initiative: 0800 111 757 / SMS: 4202",
                            "Lifeline Aotearoa: 0800 543 354 / SMS: 4357",
                            "Lifeline National Office: (64) 03 353 1136",
                            ],
            "Nicaragua": ["Hotline: 505-268-6171"],
            "Niger": ["Niger Emergency Hotline (open 24 hours): 17"],
            "Nigeria": ["The Joy Hub: 0700-843-569-482",
                        "Nigeria Hotline: (234) 8062-106-493",
                        "Lagos Hotline: 08058820777 / 09030000741",
                        "LUTH Suicide Research and Prevention Initiative (SURPIN): 09080217555 / 09034400009 / 08111909909 / 07013811143",
                        "Nigeria Suicide Prevention Initiative: 08062106493 / 08092106493"],
            "Niue": ["Niue Emergency Hotline: 999"],
            "Norway": ["Kirkens SOS: 22 40 00 40",
                       "Mental Helse: 116 123"],
            "Oman": ["Oman Emergency Hotline (open 24 hours): 999 / 112"],
            "Pakistan": ["Umang Pakistan: +92 317 4288 665",
                         "Happy KP: 0337-9216207"],
            "Palau": ["Palau Emergency Hotline (open 24 hours): 911"],
            "Palestinian Territories": ["Sawa (West Bank and Jerusalem): 121",
                                        "Aisha (Gaza): 1800 170 171"],
            "Panama": ["Te Escucho Panama (9pm-3am): 831-7600",
                       "Línea de atención emocional: 169",
                       "Instituto Nacional de Salud Mental: 523 6800",
                       "Cruz blanca Panameña: 6674 9695"],
            "Papua New Guinea": ["Hotline (day time only): +675 326 0011",
                                 "1-Tok Kaunselin Helpim Lain: +675 7150 8000"],
            "Paraguay": ["SOS Mujer (for women): 137",
                         "Paraguay Emergency Hotline (open 24 hours): 911"],
            "Peru": ["Telefono De La Esperanza: 717 003 717 / 00 51 1 273 8026"],
            "Philippines": ["Manila Lifeline Centre: (02) 8969191",
                            "Manila Lifeline Centre (Mobile phone line): 0917 854 9191",
                            "Hopeline: 804-4673 / 0917-558-4673",
                            "Hopeline (Globe & TM Subscribers): 2919"],
            "Poland": ["Olsztynski Telefon Zaufania 'Anonimowy Przyjaciel' (open 24 hours): 89 527 0000 / 89 19 288",
                       "Centrum Wsparcia Dla Osob W Stanie Kryzysu Psychicznego: 800 70 2222"],
            "Portugal": ["Voz de Apoio: 225 50 60 70",
                         "Telefone SOS Palavra Amiga: 232 42 42 82",
                         "Linha SOS-Estudante: 808 200 204"],
            "Puerto Rico": ["National Suicide Prevention Lifeline (open 24 hours, in English and Spanish): 1-800-273-TALK (8255)",
                            "NAMI Puerto Rico: (800) 950-NAMI or text 'NAMI' to 741741",
                            "PAS Line (open 24 hours): 1-800-981-0023"],
            "Qatar": ["Qatar Emergency Hotline (open 24 hours): 999 / 112"],
            "Romania": ["Romanian Alliance for Suicide Prevention (Alianţa Română de Prevenţie a Suicidului): 0800 801 200"],
            "Russia": ["Samaritans (Cherepovets): 007 (8202) 577-577"],
            "Rwanda": ["8015 Suicide Prevention Hotline (open 24 hours): 8015"],
            "Saint Helena, Ascension and Tristan da Cunha": ["Emergency Hotline: 999 / 911"],
            "St Kitts & Nevis": ["Social Emergency and Crisis Center (open 24 hours): 09 8392 4005"],
            "Saint Lucia": ["Emergency Hotline: 452-5433 / 458-2433"],
            "Saint Vincent & the Grenadines": ["The Samaritans, St. Vincent: (784) 456 1044"],
            "Samoa": ["FA'ATAUA LE OLA (FLO) / SAMOA LIFELINE (open 24 hours): 800-5433"],
            "San Marino": ["Samaritans - ONLUS: 800 86 00 22",
                           "Telefono Amico: 199 284 284"],
            "Sao Tome & Principe": ["Emergency Hotline (open 24 hours): 22-22-22"],
            "Saudi Arabia": ["Psychological Counseling Contact Center: 920 03 33 60"],
            "Senegal": ["Senegal Emergency Hotline (open 24 hours): 17"],
            "Serbia": ["Linja Telefonike e Ndihmës (KOAPS): (044) 08080",
                       "SOS Telephone: 037 23 025",
                       "Centar SRCE: 0800 300 303"],
            "Seychelles": ["Seychelles Emergency Hotline (open 24 hours): 999"],
            "Sierra Leone": ["Sierra Leone Emergency Hotline (open 24 hours): 19"],
            "Singapore": ["Samaritans of Singapore: 1800 221 4444"],
            "Slovakia": ["Linka dôvery Nezábudka: 0800 800 566"],
            "Slovenia": ["Društvo Zaupni telefon Samarijan: 116 123"],
            "Solomon Islands": ["Solomon Islands Government Emergency Hotline (open 24 hours): 911 / 60339 (Gizo) / 62911 (Munda) / 61354 (Noro) / 32338 (Tulagi)"],
            "Somalia": ["Somalia Emergency Hotline (open 24 hours): 888"],
            "South Africa": ["Adcock Ingram Depression and Anxiety Helpline: 0800 70 80 90",
                             "ChaiFM Helpline (open 24 hours): 0800 24 24 36",
                             "Cipla 24hr Mental Health Helpline: 0800 456 789",
                             "SADAG Suicide Prevention Line (open 24 hours): 0800 567 567",
                             "South Africa Suicide Crisis Helpline (open 24 hours): 0800 21 22 23 / 0800 12 13 14"],
            "South Sudan": ["Suicide Prevention & Awareness - South Sudan (SPASS): +211 921 363 237"],
            "Spain": ["Teléfono de la Esperanza: 902500002 / 717 003 717 / 91 459 00 55"],
            "Saint Vincent and the Grenadines": ["Hotline: (784) 456 1044"],
            "Sri Lanka": ["Sri Lanka Sumithrayo - Bandarawela: 011 057 2222662",
                          "Sri Lanka Sumithrayo - Colombo: 011 2692 909 / 011 2 683 555",
                          "Sri Lanka Sumithrayo - Colombo South: 011 401 094 / 011 4 404 536"
                          "Sri Lanka Sumithrayo - Panduwasnuwara: 037 2291718",
                          "Sri Lanka Sumithrayo - Kandy: 081 2234 806",
                          "Sri Lanka Sumithrayo - Matale: 066 2223521",
                          "Sri Lanka Sumithrayo - Panadura: 038 2235291"],
            "Sudan": ["Befrienders Khartoum: (249) 11-555-253"],
            "Suriname": ["Suriname Emergency Hotline (open 24 hours): 112"],
            "Swaziland": ["Swaziland Emergency Hotline (open 24 hours): 999"],
            "Sweden": ["Nagon att tala med Samaritans: (46) 31 711 2400"],
            "Switzerland": ["La Main Tendue: 143",
                            "La Main Tendue (in English): 0800 143 000"
                            "Pars Pas: 027 321 21 21"],
            "Syria": ["Syria Emergency Hotline (open 24 hours): 112"],
            "Taiwan": ["Taiwan Lifeline International (open 24 hours): 1995"],
            "Tajikistan": ["Emergency Hotline (open 24 hours): 112"],
            "Tanzania": ["Emergency Hotline (open 24 hours): 112/ 999"],
            "Thailand": ["Samaritans of Thailand: +66 (0)2 113 6789"],
            "Togo": ["VisionTogo (VTG): (+228) 90 92 22 22"],
            "Tonga": ["Lifeline Tonga: 23000 / 25144"],
            "Trinidad & Tobago": ["Lifeline (open 24 hours): +1 868-645-2800"],
            "Tunisia": ["Psychological Assistance Unit: 80 105 050",
                        "Tunisia Emergency Hotline (open 24 hours): 197"],
            "Turkey": ["Mental Health Counselling Hotline: 182"],
            "Turkmenistan": ["Turkmenistan Emergency Hotline (open 24 hours): 3"],
            "Tuvalu": ["Tuvalu Emergency Hotline (open 24 hours): 911"],
            "Turks & Caicos": ["Suicide Helpline: 183",
                               "Turks & Caicos Emergency Hotline: 911 / 999"],
            "Uganda": ["Health Hotline: +256 (0)800 200600"],
            "Ukraine": ["Lifeline Ukraine (open 24 hours): 7333" 
                        "Telephone of confidence 'Stavropyghion-058' Lviv: 058",
                        "Odessa Confidence Telephone Service: 0487 327715 / 0482 226565"],
            "United Arab Emirates": ["UAE Suicide Prevention (for Indian Expats): 800 46342"],
            "United Kingdom": ["Samaritans 116123 (toll-free) / 08457 90 90 90 (UK local rate) / 08457 90 91 92 (minicom)",
                               "The Hope Project (Men 30 to 64 yrs): 0117 428 8930",
                               "CALM: 0800 58 58 58 (National) / 0808 802 58 58 (London)",
                               "SANEline: 0300 304 7000",
                               "Breathing Space (Scotland): 0800 83 85 87"],
            "United States": ["National Suicide Prevention Lifeline: 988",
                              "Suicide.org: 1-800-784-2433",
                              "International Suicide Prevention: 702 743 4340",
                              "Hopeline: 919 231 4525 / 877 235 4525 / SMS: 741741",
                              "Crisis (SMS line): Text START to 741-741",
                              "New Hope Crisis Hotline: 714-639-4673"],
            "Uruguay": ["Uruguay Emergency Hotline (open 24 hours): 911"],
            "Uzbekistan": ["Uzbekistan Emergency Hotline (open 24 hours): 2"],
            "Vanuatu": ["Vanuatu Emergency Hotline (open 24 hours): 22100 / 112"],
            "Vatican City": ["Samaritans - ONLUS: 800 86 00 22",
                             "Telefono Amico: 199 284 284"],
            "Venezuela": ["Telefono de la Esperanza: 0241-8433308"],
            "Vietnam": ["Vietnam Emergency Hotline (open 24 hours): 113",
                        "Tâm lý NQH (open 24 hours): 19006186"],
            "Virgin Islands": ["National Suicide Prevention Lifeline: 988"],
            "Yemen": ["Yemen Emergency Hotline: 199",
                      "Family Counseling & Development Foundation Yemen: 136"],
            "Zambia": ["Lifeline Zambia: 933 (voice calls and SMS line)",
                       "Suicide Prevention Zambia: +260 960264040"],
            "Zimbabwe": ["National Council of Samaritans: (9) 650 00",
                         "Harare Samaritans: (4) 726 468 / (4) 722 000",
                         "Harare Samaritans (Toll free): 080 12 333 333",
                         "The Samaritans: (20) 635 59"],
        }
    
    def get_distance(self, text1, text2):
        return fuzz.ratio(text1, text2)

    def get_country(self, text):
        text = text.lower()
        distance = 0
        country = "Afghanistan"
        for c in self.countries.keys():
            curr_distance = self.get_distance(text, c)
            if curr_distance > distance:
                distance = curr_distance
                country = self.countries[c]
        return country
